### ISSUE TITLE
font lies

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [arkenfox/TZP#28]
here is the current fpjs2 style font enumeration

```js
function get_fpjs2() {
	/* based on https://github.com/Valve/fingerprintjs2 */
	return new Promise(resolve => {

		// vars
		let baseFonts = ['monospace','sans-serif','serif'],
			t0 = performance.now()
		// elements
		let h = document.getElementsByTagName('body')[0]
		let baseFontsDiv = document.createElement('div')
		let fontsDiv = document.createElement('div')
		let defaultWidth = {}
		let defaultHeight = {}
		let createSpan = function() {
			let s = document.createElement('spanFP')
			s.style.position = "absolute"
			s.style.left = "-9999px"
			s.style.fontSize = "256px"
			s.style.fontStyle = "normal"
			s.style.fontWeight = "normal"
			s.style.letterSpacing = "normal"
			s.style.lineBreak = "auto"
			s.style.lineHeight = "normal"
			s.style.textTransform = "none"
			s.style.textAlign = "left"
			s.style.textDecoration = "none"
			s.style.textShadow = "none"
			s.style.whiteSpace = "normal"
			s.style.wordBreak = "normal"
			s.style.wordSpacing = "normal"
			s.innerHTML = fntStrA
			return s
		}
		// creates a span and load the font to detect and a base font for fallback
		let createSpanWithFonts = function(fontToDetect, baseFont) {
			let s = createSpan()
			s.style.fontFamily = "'" + fontToDetect + "'," + baseFont
			return s
		}
		// creates spans for the base fonts and adds them to baseFontsDiv
		let initializeBaseFontsSpans = function() {
			let spans = []
			for (let index=0, length=baseFonts.length; index<length; index++) {
				let s = createSpan()
				s.style.fontFamily = baseFonts[index]
				baseFontsDiv.appendChild(s)
				spans.push(s)
			}
			return spans
		}
		// creates spans for the fonts to detect and adds them to fontsDiv
		let initializeFontsSpans = function() {
			let spans = {}
			for (let i = 0; i < fntList.length; i++) {
				let fontSpans = []
				for (let j=0, numDefaultFonts = baseFonts.length; j< numDefaultFonts; j++) {
					let s = createSpanWithFonts(fntList[i], baseFonts[j])
					fontsDiv.appendChild(s)
					fontSpans.push(s)
				}
				spans[fntList[i]] = fontSpans // Stores {fontName : [spans for that font]}
			}
			return spans
		}
		// compare
		let present = function(fontSpans) {
			let r = false
			for (let i=0; i < baseFonts.length; i++) {
				r = (fontSpans[i].offsetWidth !== defaultWidth[baseFonts[i]] || fontSpans[i].offsetHeight !== defaultHeight[baseFonts[i]])
				if (r) {return r}
			}
			return r
		}
		// stuff
		let baseFontsSpans = initializeBaseFontsSpans()
		h.appendChild(baseFontsDiv)
		for (let index=0, length = baseFonts.length; index<length; index++) {
			defaultWidth[baseFonts[index]] = baseFontsSpans[index].offsetWidth // width for the default font
			defaultHeight[baseFonts[index]] = baseFontsSpans[index].offsetHeight // height for the default font
		}
		let fontsSpans = initializeFontsSpans()
		h.appendChild(fontsDiv)
		// detect
		let found = []
		for (let i=0; i < fntList.length; i++) {
			if (present(fontsSpans[fntList[i]])) {found.push(fntList[i])}
		}
		// cleanup
		h.removeChild(fontsDiv)
		h.removeChild(baseFontsDiv)

		// resolve
		return resolve("fonts:" + hash)
	})
}
```

here is a fiddle from abraham : https://jsfiddle.net/j6gc8amy/10/

```html
<span id="show-font"></span>
```

```css
#show-font {
    --font: '';
	position: absolute !important;
    font-size: 256px !important;
    font-style: normal !important;
    font-weight: normal !important;
    letter-spacing: normal !important;
    line-break: auto !important;
    line-height: normal !important;
    text-transform: none !important;
    text-align: left !important;
    text-decoration: none !important;
    text-shadow: none !important;
    white-space: normal !important;
    word-break: normal !important;
    word-spacing: normal !important;
}

#show-font::after {
    font-family: var(--font);
    content: 'mmmmmmmmmmlli';
}
```

```js
const span = document.getElementById('show-font')
const baseFonts = ['monospace', 'sans-serif', 'serif']
const base = {}
baseFonts.forEach(font => {
	span.style.setProperty('--font', font)
	const { width, height } = span.getClientRects()[0]
	base[font] = { width, height }
	return	
})

const families = fontList.reduce((acc, font) => {
	baseFonts.forEach(baseFont => acc.push(`'${font}', ${baseFont}`))
	return acc
},[])
const detected = new Set()


families.forEach(family => {
    span.style.setProperty('--font', family)
	const basefont = /, (.+)/i.exec(family)[1]
    const { width, height } = span.getClientRects()[0]
	const supported = (
		width != base[basefont].width || height != base[basefont].height
	)
	if (supported) {
		const font = /\'(.+)\'/i.exec(family)
		return detected.add(font[1])
	}
	return
})
console.log(`${detected.size}/${fontList.length}`, [...detected].join('\n'))

})()
```

also see https://github.com/abrahamjuliot/creepjs/issues/100

I tested this with chameleon's font protection: TZP reports 0 fonts for `fpjs2` and `font fallback` methods. Tested fiddle with and without chameleon = same result: i.e it found the fonts

more to follow
