### ISSUE TITLE
expand screen methods

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [arkenfox/TZP#29]
reminder
- [x] use available screen, not screen .. in FP metrics, as available has more entropy
   - n/a : the loose fingerprint collects everything and anything it wants

items: extra conversation at https://github.com/abrahamjuliot/creepjs/issues/97
- [x] large and small *vw/*vh
- [x] dynamic toolbar: auto results from other measurements
- [x] documentElement.clientHeight
- [x] use an element such as in FS test
- [x] iframe
- [ ] intersectionObserver
- [ ] matchMedia object
- [ ] detect screen via `getComputedStyle`: https://jsfiddle.net/jrnca3wh/
- [ ] `@media`: https://jsfiddle.net/w8qxu1p2/1/
- [ ] `@import` can access media queries: https://jsfiddle.net/873kspn4/1/

**Comment by Thorin-Oakenpants** [comment]
assigning @abrahamjuliot 🤣 🤣 🤣

**Comment by Thorin-Oakenpants** [comment]
just a random idea
- using JS to generate css `@media` rules, e.g. `min-device-width` and `min-device-height`
- width would set background color
- height would set color
- use the width/height to determine the color value
   - e.g. width 500 = `rgb(5,0,0)`, 2560 = `rgb(25,6,0)`
- apply to a div
- this would only have to happen once

Read the div's colors back to return the width/height. i.e a JS approach to read back pure css (which extensions can't alter)

**Comment by Thorin-Oakenpants** [comment]
actually .. I already have the css rules, and can just use the after pseudo element

```css
#cssPCS:after{content:"not supported"}
@media (prefers-color-scheme:light){#cssPCS:after{content:"light";}}
@media (prefers-color-scheme:dark){#cssPCS:after{content:"dark";}}
@media (prefers-color-scheme:no-preference){#cssPCS:after{content:"no-preference";}} /* obsolete FF79+: 1643656 */
```

```js
function getContent(id, pseudo) {
	try {
		let item = window.getComputedStyle(document.querySelector(id), pseudo)
		item = item.getPropertyValue("content")
		if (item == "none") {console.warn(id, item)}
		return item.replace(/"/g,"")
	} catch(e) {
		console.error(id, e.name, e.message)
		return "error"
	}
}
```

Since some extensions block matchMedia (e.g. Cydec), I now use this as the real value

```js
	// snip: x = window.matchMedia .. etc
	let x2 = getContent('#cssPCS',':after')
	if (x2 !== "none" && x2 !== "error" ) {x = x2} // replace matchmedia value with x2
```

Of course the wee media.css file (26k) I can move up to the header, but not sure about 500kb of screen.css + window.css - but something to think about

**Comment by Thorin-Oakenpants** [comment]
^ actually, some items might return `"none"`, which after stripping quotes marks fail, so instead use some unique string

```css
#cssH:after{content:"not supported";}
@media (hover:none){#cssH:after{content:"none";}}
@media (hover:hover){#cssH:after{content:"hover";}}
```
