### ISSUE TITLE
zoom resistance: is futile and not needed, esp if we know the zoom level

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [arkenfox/TZP#49]
### new OP

- [x] undo: screen as highest vs lowest to avoid orientation bias
- [x] undo: returning screen at 100% zoom
- return value(s) for
   - [x] scrollbar width: doc and element
   - [x] css line height
   - [x] mathml
- increase metrics
   - [x] devicePixelRatio
   - [x] isFF calculated zoom level

---

### original OP

Make **_collected metrics_** zoom/system-scaled resistant: so far these are the only items that aren't

- screen
   - FF only: when returning actual screen measurements: use devicePixelRatio PoC to calculate at 100% if not android
   - ~~screen: add aspect ratio (highest x lowest: to avoid orientation) to collected metrics~~ adds nothing extra: the aspect ratio is based on the screen metrics anyway: fake or real
   - record screen as highest vs lowest to avoid orientation bias

- ~~domrect: FF: use aspect ratios, % of overall measurement(s) - see original OP below~~
- ~~unicode glyphs (offset, getClient, getBounding)~~
- ~~textmetrics: width, actualBoundingBoxRight~~
- ~~canvas: if Arial is blocked~~

---
original OP

just an idea: probably won't work with chromium: e.g. like that known test

We still run and measure the eight metrics etc
- lies: two-pass, shift, known value
- then we use the data to calculate zoom-resistant (or more zoom resistant) information
   - aspect ratios of each item
   - get the total area used to house everything and then return each item's area as a % of that
   - ^ same but it's positions as a % of the total width/length

The new calculation should have as much entropy

**Comment by Thorin-Oakenpants** [comment]
@abrahamjuliot edited OP ... so, me not being a css junkie, is it possible to make the font sizes in the the unicode glyphs test, zoom resistant?

**Comment by abrahamjuliot** [comment]
I have not fully absorbed the unicode glyphs test, but `position: absolute` should take care of that. 

```css
position: absolute !important;`
left: -9999px !important;
```

**Comment by Thorin-Oakenpants** [comment]
I did harden my `offscreen` style rule with `left` and added some `!important` - thanks. I'm measuring the divs and spans, so position doesn't matter

I also tried `22px` (same result)
```html
<div id="ugDiv" class="normalized" style='font-size: 22pt;'>
	<span id="ugSpan"><span id="ugSlot"></span></span>
</div>
```

```css
.normalized {
	font-family: none;
	font-style: normal;
	font-variant: normal;
	font-weight: normal;
	line-height: normal;
	text-transform: none;
	text-align: left;
	text-decoration: none;
	text-shadow: none;
	white-space: normal;
	word-break: normal;
	word-spacing: normal;
}
#ugSpan {font-size: 10000%;}
```

Not sure if there is a way around this. Zooming changes text sizes
![measure](https://user-images.githubusercontent.com/16656956/115100986-387e9b00-9f30-11eb-824f-1ad5f6d4a7a7.png)
